first version info profile
maryanchuk04/stud-city pull request #103
Opened 2023-03-06 19:02 UTC by Vova-Romaniuk

dev
## GitHub Project

* [Main GitHub Project ticket](https://github.com/users/maryanchuk04/projects/3)

## Code reviewers

- [ ] @maryanchuk04 
- [ ] @Serhiy-dotcom 

### Second Level Review

- [ ] @Varvara-Maria 

## Summary of issue

Edit profile info UI Part

## Summary of change

Create new page edit profile
made changes in  previosly created files

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-03-06 19:13 UTC, Varvara-Maria requested changes

2023-03-06 19:13 UTC, Varvara-Maria commented on StudCity.Frontend/src/pages/RegistrationComplete/steps/UploadAvatar.jsx
> +	useEffect(() => {
I think we don`t need that console.log

2023-03-06 20:12 UTC, Serhiy-dotcom requested changes
fix this and similar issues in your files

2023-03-06 20:12 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/UI/CustomDialog/index.jsx
> +function CustomDialog({ className = "", children, close }) {
rename close prop into handleClose as this more epropriate naming convention to use

2023-03-06 20:12 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/pages/Profile/EditProfile/index.jsx
> +//import UploadImageInput from "../../../UI/fields/UploadImageInput";
remove comment please

2023-03-06 20:12 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/pages/Profile/EditProfile/index.jsx
> +				?
you can remove ternary and use absolut AND instead

2023-03-06 20:12 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/pages/Profile/EditProfile/index.jsx
> +				?
here as well

2023-03-06 20:12 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/pages/Profile/EditProfile/index.jsx
> +									<div className="rounded-tl-[60px] overflow-hidden w-full  h-56" key = {index}>
don't use index as key, better use element instead if it's unique

2023-03-06 20:12 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/pages/Profile/EditProfile/index.jsx
> +								src={backgroundImage === "" ? DEFAULT_BACKGROUND_URL : backgroundImage}
better use just backgroundImage and set DEFAULT_BACKGROUND_URL directly into state as default

2023-03-06 20:12 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/pages/Profile/EditProfile/index.jsx
> +									src={avatar === "" ? "/images/defaultAvatar.png" : avatar}
same here

2023-03-06 20:12 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/pages/Profile/EditProfile/index.jsx
> +								<span className={`${spanWithInputsBlocks}`}>Birthday</span>
no need to use tildas here, use className={spanWithInputsBlocks} like this

2023-03-06 20:12 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/pages/Profile/EditProfile/index.jsx
> +							<div className={`${inputBlock}`}>
same here
PS: fix it in all places

2023-03-06 20:12 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/pages/Profile/EditProfile/index.jsx
> +									placeholder={"Input your phone"}
no need to use curly brackets

2023-03-06 20:12 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/utils/constants.js
> +	"/images/FlagUkraine.jpeg",
remove duplicate values

2023-03-07 11:10 UTC, maryanchuk04 requested changes

2023-03-07 11:10 UTC, maryanchuk04 commented on StudCity.Frontend/src/UI/CustomDialog/index.jsx
> +		<div className={`absolute z-50 w-full h-screen bg-[rgba(0,0,0,0.5)] ${className}`}>
Pls change this color type to HEX

2023-03-07 11:10 UTC, maryanchuk04 commented on StudCity.Frontend/src/pages/RegistrationComplete/steps/UploadAvatar.jsx
> +	useEffect(() => {
I think we don`t need that useEffect

2023-03-07 11:10 UTC, maryanchuk04 commented on StudCity.Frontend/src/pages/RegistrationComplete/steps/UploadAvatar.jsx
> +		<div className={`flex w-full h-full flex-col ${className} `}>
space in the end of line

2023-03-07 11:10 UTC, maryanchuk04 commented on StudCity.Frontend/src/UI/fields/UploadImageInput.jsx
> +				{children}
I think we must add buttonLabel props. No need to use children here.

2023-03-09 18:21 UTC, Serhiy-dotcom approved these changes
kudos!

2023-03-09 18:32 UTC, maryanchuk04 approved these changes
Good job)

2023-03-09 18:42 UTC, merged