created Contact us page
maryanchuk04/stud-city pull request #114
Opened 2023-03-14 19:26 UTC by Varvara-Maria

dev
## GitHub Project

* [Main GitHub Project ticket](https://github.com/users/maryanchuk04/projects/3)

## Code reviewers

- [ ] @maryanchuk04 

### Second Level Review

- [ ] @Vova-Romaniuk 

## Summary of change

Created page where user can send message for website administrator.

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-03-14 19:41 UTC, Serhiy-dotcom requested changes

2023-03-14 19:41 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/pages/ContactUs/index.jsx
> +            <img className='h-screen z-0' src="https://images.unsplash.com/photo-1523966211575-eb4a01e7dd51?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fGNvbnRhY3QlMjB1c3xlbnwwfHwwfHw%3D&auto=for
it's probably better to put this image inside global constants file, or in this file locally

2023-03-14 19:41 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/pages/ContactUs/index.jsx
> +                        onChange={(e) => setDetails({ ...details, firstName: e.target.value })}
consider changing the logic for handling changes in all inputs and textarea

2023-03-14 20:23 UTC, Serhiy-dotcom approved these changes
kudos!

2023-03-15 19:24 UTC, maryanchuk04 approved these changes

2023-03-16 11:01 UTC, Vova-Romaniuk approved these changes

2023-03-16 12:27 UTC, Serhiy-dotcom approved these changes

2023-03-16 12:27 UTC, merged