press enter send an message in chat
maryanchuk04/stud-city pull request #138
Opened 2023-04-13 18:43 UTC by Vova-Romaniuk

dev
## GitHub Project

* [Main GitHub Project ticket](https://github.com/users/maryanchuk04/projects/3)

## Code reviewers

- [ ] @maryanchuk04 
- [ ] @Serhiy-dotcom 

### Second Level Review

- [ ] @Varvara-Maria 

## Summary of issue

press enter then send messge

## Summary of change

change div on form and create extra condition for "shift + enter" 

## Testing approach

ToDo

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-04-13 18:59 UTC, Serhiy-dotcom approved these changes

2023-04-20 09:52 UTC, maryanchuk04 requested changes

2023-04-20 09:52 UTC, maryanchuk04 commented on StudCity.Frontend/src/components/Sender/index.jsx
> +				onKeyDown={(event) => handleKeyDowm(event)}
You can use only `onKeyDown={handleKeyDown}`

2023-05-17 05:50 UTC, maryanchuk04 approved these changes

2023-05-17 05:50 UTC, merged