107 edit profile settings
maryanchuk04/stud-city pull request #168
Opened 2023-07-09 13:43 UTC by Vova-Romaniuk

dev
## GitHub Project

* [Main GitHub Project ticket](https://github.com/users/maryanchuk04/projects/3)

## Code reviewers

- [ ] @maryanchuk04 
- [ ] @Serhiy-dotcom 

### Second Level Review

- [ ] @Varvara-Maria 

## Summary of issue

Create settings page with possibility selected (theme interface and language etc.)

## Summary of change

Created all the necessary components for perform tasks

## Testing approach

ToDo

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-07-09 14:25 UTC, Serhiy-dotcom reviewed
Please check comments

2023-07-09 14:25 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/pages/Profile/EditProfile/ProfileSettings/index.jsx
> +						return React.cloneElement(child, { setExpanded: setExpanded, expanded: expanded });
I see what you are doing here, but is it possible to omit using React native methods? I would suggest to declare HeaderAccord directrly inside Accord component, and just pass HeaderAccord text through props in Accord component, that's one option that I see how to omit this kind of logic

2023-07-09 14:38 UTC, maryanchuk04 requested changes

2023-07-09 14:38 UTC, maryanchuk04 commented on StudCity.Frontend/src/UI/DatePicker/CustomHeader.jsx
> +	const buttonStyles = "border-2 bg-white border-borderGray rounded-full px-2 py-1";
Rename color name pls

2023-07-09 14:38 UTC, maryanchuk04 commented on StudCity.Frontend/src/components/Scroller/index.jsx
> +		<div className='h-full w-full flex overflow-y-auto'>
Are you sure that this does not affect other components? You might want to add a className property to this component

2023-07-09 14:38 UTC, maryanchuk04 commented on StudCity.Frontend/src/pages/Profile/EditProfile/ProfileSettings/index.jsx
> +			<Accord isExpanded={true}>
I think it's a bad idea to do it that way!

Why not make components if they were called Accordion, in which the isExpanded title and children properties would wake up, this component should be more reusable, and we can transfer your toggles to another component, they can be useful

2023-07-09 14:38 UTC, maryanchuk04 commented on StudCity.Frontend/src/pages/Profile/EditProfile/ProfileSettings/index.jsx
> +				React.Children.map(children, (child, index) => {
KISS!!!

2023-07-09 14:39 UTC, maryanchuk04 commented
@Vova-Romaniuk Please review all comments

2023-07-12 09:39 UTC, Serhiy-dotcom approved these changes
Nice work!

2023-07-12 09:43 UTC, maryanchuk04 approved these changes
Great job!

2023-07-12 09:47 UTC, merged