16 registration service
maryanchuk04/stud-city pull request #26
Opened 2023-02-09 17:09 UTC by maryanchuk04

This PR contain full **registration** new User account.

I create some:
-  services
- api controller
- migrations

2023-02-09 19:13 UTC, Vova-Romaniuk approved these changes

2023-02-09 19:48 UTC, Serhiy-dotcom requested changes
Please fix the issues above.

2023-02-09 19:48 UTC, Serhiy-dotcom commented on StudCity.Backend/StudCity.API/Program.cs
>          b => b.MigrationsAssembly("StudCity.Db")), ServiceLifetime.Scoped);
Please add additional paragraph for third parameter

2023-02-09 19:48 UTC, Serhiy-dotcom commented on StudCity.Backend/StudCity.Application/Helpers/PasswordHasherService.cs
> +        return BCrypt.Net.BCrypt.Verify(password,hashingString);
add a space before 'hashingString' prop

2023-02-09 19:48 UTC, Serhiy-dotcom commented on StudCity.Backend/StudCity.Application/Providers/TokenProvider.cs
> +
remove paragraph

2023-02-10 07:40 UTC, Serhiy-dotcom approved these changes
Very good!

2023-02-10 07:40 UTC, merged