Email confirmation template
maryanchuk04/stud-city pull request #27
Opened 2023-02-09 20:05 UTC by Varvara-Maria

I made email confirmation template, please review it

2023-02-09 20:23 UTC, Serhiy-dotcom requested changes

2023-02-09 20:23 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/App.js
> +
remove paragraph please

2023-02-09 20:23 UTC, Serhiy-dotcom commented on StudCity.Backend/StudCity.API/Templates/ConfirmationLetter.html
> +    <div style='display: flex; justify-content: center; font-weight: 500; color:black; font-size: 30px;  margin-bottom: 20px;'>
replace single quotes with double quotes

2023-02-09 20:23 UTC, Serhiy-dotcom commented on StudCity.Backend/StudCity.API/Templates/ConfirmationLetter.html
> +    <p style=" font-family: 'Hind', sans-serif; font-weight: 600; margin: 20px 0; font-size: 18px;">
remove a space before font-family

2023-02-09 20:23 UTC, Serhiy-dotcom commented on StudCity.Backend/StudCity.API/Templates/ConfirmationLetter.html
> +    <img style="height: 450px; margin: 0;" src="https://niceillustrations.com/wp-content/uploads/2022/01/Verification-Code-color-800px.png" alt="">
add a value to alt attribute

2023-02-09 20:23 UTC, Serhiy-dotcom commented on StudCity.Backend/StudCity.API/Templates/ConfirmationLetter.html
> +        <p style="padding: 15px; background-color: #e9e8e8; border-radius: 10px; margin: 0 15px 0 0; ">{5}</p>
and some spaces above at the end of style attribute value

2023-02-09 20:27 UTC, maryanchuk04 approved these changes
Fix Serhio comments and send request again) 

I'm waiting...

2023-02-10 07:29 UTC, maryanchuk04 approved these changes
You can merge this PR.
Great job.

2023-02-10 07:30 UTC, Serhiy-dotcom approved these changes
Great work, go ahead and merge!

2023-02-10 07:33 UTC, merged