Authenticate page create
maryanchuk04/stud-city pull request #30
Opened 2023-02-10 13:16 UTC by Vova-Romaniuk

Created Authenticate page.
Create form with input type(password) validation, input type(email), create button google authorized and default button submit

2023-02-10 13:26 UTC, maryanchuk04 requested changes
Pls check small comments and push again

2023-02-10 13:26 UTC, maryanchuk04 commented on StudCity.Frontend/public/index.html
> +  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
Please format this lines...

2023-02-10 13:26 UTC, maryanchuk04 commented on StudCity.Frontend/src/App.js
Remove unnecessary paragraph

2023-02-10 13:26 UTC, maryanchuk04 commented on StudCity.Frontend/src/UI/Fields/TextField.jsx
> +
Again

2023-02-10 14:54 UTC, maryanchuk04 approved these changes

2023-02-10 15:47 UTC, Serhiy-dotcom requested changes
Please change issues below

2023-02-10 15:47 UTC, Serhiy-dotcom commented on StudCity.Frontend/.eslintrc.json
> +        "react/prop-types": "off",
please put this rule at the top of 'rules' object

2023-02-10 15:47 UTC, Serhiy-dotcom commented on StudCity.Frontend/public/index.html
> +<!--
add a tab before comment declaration

2023-02-10 15:47 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/App.css
> +*{
move this style rule to the index.css file, and delete this App.css file

2023-02-10 15:47 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/UI/Button.jsx
> +            className={`rounded-2xl bg-[#486645] disabled:cursor-not-allowed text-[#F9FCF8] mt-3 h-16 w-1/1 font-normal${className}`}
add a space before using '$' sign, for better future use of className prop

2023-02-10 15:47 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/UI/Button.jsx
> +function Button({ children, className, disabled }) {
add a default value of 'false' for disabled prop so that it wouldn't be required in the future

2023-02-10 15:47 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/UI/Fields/PasswordTextField.jsx
> +	const [passwordError, setPasswordErr] = useState("");
please make the same ending for both a variable and set-function

2023-02-10 15:47 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/UI/Fields/PasswordTextField.jsx
> +		}else{
you don't need this else block please remove it

2023-02-10 15:47 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/UI/Fields/PasswordTextField.jsx
> +		errMsg.length !== 0 ? setDisabled(true) : setDisabled(false)
I think it's better to use if else here, as you don't return anything with ternari operator, but just using a function

2023-02-10 15:47 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/UI/Fields/PasswordTextField.jsx
> +				: hidden &&
you don't need 'hidden &&' here, it will work without it

2023-02-10 15:47 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/UI/GoogleButton.jsx
> +		<button type='button'  className='flex break-inside bg-white text-[#486645] border-2 border-[#486645] rounded-3xl px-6 py-3 mb-4 w-full   h-16 '>
I see a lot of using of color #486645, please add it to tailwind.config.js, and use a name for it(in other files as well such as Button, TextField etc).
And remove unneeded spaces before h-15 class

2023-02-10 15:47 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/pages/authenticate/Authenticate.jsx
> +							className = {""} type = {"email"}
add a default value for className prop of TextField and other components where needed

2023-02-10 15:47 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/pages/authenticate/Authenticate.jsx
> +							placeholder = {"Enter your email"}
no need to use curly brackets for placeholder value if it's a string

2023-02-12 12:35 UTC, maryanchuk04 approved these changes
I`m approve this PR, but please fix small errors

2023-02-12 12:35 UTC, maryanchuk04 commented on StudCity.Frontend/src/UI/Fields/PasswordTextField.jsx
> +function PasswordTextField({ className = " ", placeholder, required, setDisabled }) {
You can write only  = ""  without spaces

2023-02-12 12:35 UTC, maryanchuk04 commented on StudCity.Frontend/src/UI/Fields/TextField.jsx
> +function TextField({ className = " ", placeholder, type, required }) {
You can write again only brackets

2023-02-12 12:35 UTC, maryanchuk04 commented on StudCity.Frontend/src/UI/GoogleButton.jsx
> +		<button type='button' className='flex break-inside bg-white text-[#486645] border-2 border-[#486645] rounded-3xl px-6 py-3 mb-4 w-full h-16'>
Please, your write styles for this color (#486645), u can use it

2023-02-12 12:35 UTC, maryanchuk04 commented on StudCity.Frontend/src/pages/authenticate/Authenticate.jsx
> +					<h6 className="w-full text-center font-normal text-lg text-[#486645]">Please enter your details</h6>
Again you use #486645 color

2023-02-12 12:35 UTC, maryanchuk04 commented on StudCity.Frontend/src/pages/authenticate/Authenticate.jsx
> +						<a className="w-full text-center ml-1 font-medium text-base text-[#486645]" href="">Forgot password</a>
Again

2023-02-12 14:07 UTC, maryanchuk04 approved these changes
Pls fix small problem

2023-02-12 14:07 UTC, maryanchuk04 commented on StudCity.Frontend/src/UI/Fields/PasswordTextField.jsx
> +	const primaryGray = "#506466";
i think constants must be named in uppercase (PRIMARY_GRAY)

2023-02-12 14:07 UTC, maryanchuk04 commented on StudCity.Frontend/src/pages/authenticate/Authenticate.jsx
> +							className = ""
Button have parrams by default, you dont need props className

2023-02-12 14:07 UTC, maryanchuk04 commented on StudCity.Frontend/src/pages/authenticate/Authenticate.jsx
> +						<GoogleButton></GoogleButton>
Why u don't use `<GoogleButton /> `?

2023-02-12 14:07 UTC, Serhiy-dotcom approved these changes
Please fix comments in file 'StudCity.Frontend/src/UI/Fields/PasswordTextField.jsx'

2023-02-12 14:20 UTC, maryanchuk04 approved these changes

2023-02-12 14:20 UTC, merged

2023-02-12 14:21 UTC, Serhiy-dotcom approved these changes