20 create submit email page
maryanchuk04/stud-city pull request #58
Opened 2023-02-16 18:54 UTC by Varvara-Maria

i created submit email page

2023-02-16 19:48 UTC, Serhiy-dotcom requested changes
Please fix changes below

2023-02-16 19:48 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/App.js
> +import VerifyEmail from "./pages/verify-email/VerifyEmail";
please use naming index.jsx file instead of VerifyEmail.jsx so that the import route look like in lines 8-9

2023-02-16 19:48 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/pages/verify-email/VerifyEmail.jsx
> +            <Svg type='verifyWave' className='rotate-[270deg]  absolute left-[-45%] top-[44%]'/>
use '-left[45%]' instead of 'left-[-45%]' as docs suggest
PS: in other places as well

2023-02-16 19:48 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/pages/verify-email/VerifyEmail.jsx
> +    const [numbers, setNumbers] = useState({
use an array instead of an object

2023-02-16 19:48 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/pages/verify-email/VerifyEmail.jsx
> +                <TextField
render these 6 TextField components by mapping through numbers state array

2023-02-19 17:37 UTC, Serhiy-dotcom approved these changes

2023-02-19 17:37 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/pages/verify-email/index.jsx
> +        console.log(verifyMessage);
remove console.log please

2023-02-19 17:37 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/pages/verify-email/index.jsx
> +    const [numbers, setNumbers] = useState(["", "", "", "", "", ""]);
change the naming for example 'verifyNumbersArray', or ask our PM for a suggestion

2023-02-20 16:02 UTC, maryanchuk04 requested changes

2023-02-20 16:02 UTC, maryanchuk04 commented on StudCity.Frontend/src/pages/verify-email/index.jsx
> +    const [numbers, setNumbers] = useState(["", "", "", "", "", ""]);
I agree with @Serhiy-dotcom  we must change this state name. I think so.

2023-02-20 16:02 UTC, maryanchuk04 commented on StudCity.Frontend/src/pages/verify-email/index.jsx
> +        <div className='w-[70%] shadow-md h-[85%] bg-white z-10 mx-auto my-0 absolute left-[15%] top-[8%] text-center'>
You can use h-5/6 (it is 83.333...%) 
@Serhiy-dotcom What do you think?

2023-02-20 17:13 UTC, Vova-Romaniuk approved these changes

2023-02-20 19:22 UTC, maryanchuk04 approved these changes

2023-02-20 19:22 UTC, merged