Not found page done
maryanchuk04/stud-city pull request #59
Opened 2023-02-16 19:10 UTC by Vova-Romaniuk

2023-02-16 19:55 UTC, Serhiy-dotcom requested changes
Please fix issues below

2023-02-16 19:55 UTC, Serhiy-dotcom commented on StudCity.Frontend/public/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Bodoni+Moda:ital,opsz,wght@0,6..96,700;0,6..96,800;1,6..96,700&family=Dancing+Script:wght@700&family=Playfair+Display:ital,wght@0,400;0,500;0,
I see you importing a few fonts including Roboto, but we have Roboto already imported on lines 13-15, please delete those lines or remove Roboto from line 18

2023-02-16 19:55 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/App.js
> +		element: <NotFound></NotFound>
use self-closing tag instead paired one

2023-02-16 19:55 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/App.js
> +import NotFound from "./pages/NotFound/NotFound";
rename NotFound.js file to index.jsx instead so that naming would be the same as for lines 8-9

2023-02-16 19:55 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/pages/NotFound/NotFound.js
> +				<div className={`absolute left-[-5%] top-3/4 w-[400px] h-[400px] bg-[${dark}] rounded-[50%] `}></div>
user '-left[5%]' instead of 'left-[-5%]' as official docs suggests 
PS: in other places as well

2023-02-17 13:06 UTC, Serhiy-dotcom approved these changes

2023-02-17 13:06 UTC, Serhiy-dotcom commented on StudCity.Frontend/src/pages/NotFound/index.jsx
> +
please remove this enter

2023-02-17 13:25 UTC, maryanchuk04 approved these changes
Cool <3

2023-02-17 13:28 UTC, merged