fixed a bug
maryanchuk04/stud-city pull request #97
Opened 2023-03-03 12:44 UTC by Varvara-Maria

dev
## GitHub Project

* [Main GitHub Project ticket](https://github.com/users/maryanchuk04/projects/3)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-03-03 15:59 UTC, Vova-Romaniuk requested changes

2023-03-03 15:59 UTC, Vova-Romaniuk commented on StudCity.Backend/StudCity.API/wwwroot/html/ConfirmationLetter.html
> +    <div style='display: flex; font-weight: 500; color:black; font-size: 30px; margin-bottom: 20px;  margin: 20px 0 20px 50px;'>
here something else needs bacause it`s don`t work on my phone

2023-03-03 16:03 UTC, maryanchuk04 commented on StudCity.Backend/StudCity.API/wwwroot/html/ConfirmationLetter.html
> +    <p style="font-family: 'Hind', sans-serif; text-align: center; font-weight: 600; margin: 35px 0; font-size: 18px;">
This does not work. Try another approach

2023-03-05 12:16 UTC, maryanchuk04 approved these changes

2023-03-06 19:25 UTC, Serhiy-dotcom approved these changes

2023-03-09 13:54 UTC, Vova-Romaniuk approved these changes

2023-03-09 16:40 UTC, merged